In [176]:
import pandas as pd
import numpy as np

In [177]:
data = pd.read_csv('data/TC_AC_MNTHNG_CREDT_EXAMIN_20201204155835.csv')

In [168]:
data_copy = data.copy()

In [169]:
data_copy.drop(['시도명', '시군구명', '행정동명', '기업번호', '보증번호'], axis = 1, inplace = True)

In [170]:
data_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37972 entries, 0 to 37971
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   기준년월      37972 non-null  object
 1   성별코드      37972 non-null  object
 2   연령대코드     37972 non-null  int64
 3   사업자등록번호   37972 non-null  object
 4   조사종류명     37972 non-null  object
 5   부실구분명     37972 non-null  object
 6   대위변제구분명   37972 non-null  object
 7   회계년도      37972 non-null  int64
 8   자기자본금액    37972 non-null  int64
 9   당기순이익금액   37920 non-null  float64
 10  당기매출금액    37972 non-null  int64
 11  총차입금액     37972 non-null  int64
 12  운영자금차입금액  36774 non-null  float64
 13  부채비율      37972 non-null  float64
dtypes: float64(3), int64(5), object(6)
memory usage: 4.1+ MB

In [198]:
# index 변경
data_copy.set_index('사업자등록번호', inplace = True)

In [199]:
# 결측치 제거
data_copy.dropna(inplace = True)

In [200]:
# 기준년월 datetime으로 변환
import datetime
data_copy['기준년월'] = pd.to_datetime(data_copy['기준년월'], format = "%Y-%m")

In [201]:
# 원핫 인코딩
ohe = OneHotEncoder()
df = data_copy[['성별코드', '연령대코드', '조사종류명', '대위변제구분명']]
df_ohe = ohe.fit_transform(df)
df_ohe = df_ohe.toarray()

In [202]:
cols = ohe.get_feature_names()

In [203]:
df_ohe = pd.DataFrame(df_ohe, columns = cols, index = df.index)
df_ohe

,x0_F,x0_M,x1_20,x1_30,x1_40,x1_50,x1_60,x1_70,x1_80,x2_소액심사,x2_정식심사,x3_대위변제,x3_대위변제해제
사업자등록번호,,,,,,,,,,,,,
11917*****,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
14181*****,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
12481*****,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
12681*****,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
13281*****,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14102*****,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
20481*****,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
12381*****,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
27988*****,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
12708*****,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0

In [204]:
df_ohe = pd.DataFrame(df_ohe, columns = cols, index = df.index)

In [205]:
result = pd.concat([data_copy, df_ohe], axis = 1)
result

,기준년월,성별코드,연령대코드,조사종류명,부실구분명,대위변제구분명,회계년도,자기자본금액,당기순이익금액,당기매출금액,...,x1_30,x1_40,x1_50,x1_60,x1_70,x1_80,x2_소액심사,x2_정식심사,x3_대위변제,x3_대위변제해제
사업자등록번호,,,,,,,,,,,,,,,,,,,,,
11917*****,2020-10-01,F,60,정식심사,정상해지,대위변제해제,2009,293000000,62000000.0,1287000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
14181*****,2020-10-01,M,30,정식심사,정상해지,대위변제해제,2015,466000000,446000000.0,3135000000,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
12481*****,2020-10-01,M,60,정식심사,정상해지,대위변제해제,2008,623000000,231000000.0,2364000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
12681*****,2020-10-01,M,50,정식심사,정상해지,대위변제해제,2010,600000000,264000000.0,6972000000,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
13281*****,2020-10-01,M,60,정식심사,전액회수,대위변제해제,2005,0,16000000.0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14102*****,2020-10-01,M,50,정식심사,정상해지,대위변제해제,2011,42000000,32000000.0,816000000,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
20481*****,2020-10-01,M,50,정식심사,정상,대위변제해제,2017,624000000,54000000.0,2605000000,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
12381*****,2020-10-01,M,60,정식심사,특수채권,대위변제,2005,0,11000000.0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
27988*****,2020-10-01,M,50,정식심사,정상,대위변제해제,2018,120000000,22000000.0,1220000000,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
12708*****,2020-10-01,M,60,소액심사,정상,대위변제해제,2011,0,54000000.0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0

In [208]:
# '부실구분명' => '정상' / '부실'로 구분
data['부실구분명'].value_counts()

정상해지    16641
정상      12588
특수채권     3673
구상채권     2633
전액회수     1628
관리종결      497
보증부실      192
매각        120
Name: 부실구분명, dtype: int64

In [219]:
result = data['부실구분명'].replace('정상해지', '정상')

In [220]:
result2 = result.replace(['특수채권', '구상채권',' 전액회수', '관리종결', '관리부실', '매각' ], '부실')

In [221]:
result2

0        정상
1        정상
2        정상
3        정상
4        정상
         ..
37967    정상
37968    정상
37969    부실
37970    정상
37971    정상
Name: 부실구분명, Length: 37972, dtype: object

In [145]:
# 모듈 import
from sklearn.preprocessing import StandardScaler # 얘도 선형방식을 사용해서 전처리해줘야 성능 향상
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

from sklearn.model_selection import train_test_split

In [146]:
# X, y 나누기
y = data_copy['부실구분명']
X = data_copy.drop(['부실구분명'], axis = 1)

In [147]:
# Train, Test로 나누기
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify = y, )

In [ ]:
result.drop(['성별코드','연령대코드','조사종류명','대위변제구분명'],axis = 1).columns